### ISSUE TITLE
Unable to remove app before test

### ISSUE THREAD

**Issue by denicolodavide** [detroit-labs/katalon-mobile-util#16]
Invoking:

```Device.startApp([iosApp, androidApp], true)```

with parameters "removeAppBeforeTest=true"

I receive a stacktrace exception that you can see here:
```
java.lang.NoSuchMethodError: io.appium.java_client.AppiumDriver.removeApp(Ljava/lang/String;)Z
    at com.detroitlabs.katalonmobileutil.device.Device.startApp(Device.java:77)
    at com.detroitlabs.katalonmobileutil.device.Device.startApp(Device.java:53)
    at com.detroitlabs.katalonmobileutil.device.Device$startApp.call(Unknown Source)
    at Utilities_7_Functionality_StartAppSwitcherDev.run(Utilities_7_Functionality_StartAppSwitcherDev:31)
    at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
    at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
    at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
    at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
    at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
    at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
    at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
    at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
    at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
    at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
    at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
    at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
    at TempTestSuite1562252659129.run(TempTestSuite1562252659129.groovy:35)
```

**Comment by ctrevarthen** [comment]
Hi @skydenicoloda, 

Thanks for reaching out. Can you please let me know what version of Katalon Studio you're using (and the version of Appium)?

The `startApp` function is relying on Appium's `java_client` library, which comes with Katalon Studio. If there's an updated version of the library, it could break compatibility with katalon-mobile-util, so I'm interested to hear what version you're using.

Thanks,

Chris

**Comment by denicolodavide** [comment]
Katalon version is 6.2.0-16161690e while appium version is 1.13.0. Tell me if other informations needed, thanks very much :)

**Comment by ctrevarthen** [comment]
Thanks! I’ll try to reproduce your issue.

**Comment by ctrevarthen** [comment]
Hi @skydenicoloda 

So far, I'm not able to reproduce your issue with Appium 1.12.1 or 1.13.0 (although Katalon Studio 6.2.x only officially supports Appium 1.12.1 right now). 

Could you please tell me which version of katalon-mobile-util you're using as well?

Also, if you right-click on the `Device.startApp` function in your test case and choose "Open Declaration", does it take you into the source code of `Device.class`? If so, and you find line 77 where it says `driver.removeApp(bundleId);` can you also right-click and choose "Open Declaration" on `removeApp`? You might see a message about "Source not found", and that's OK. I'm curious what it says for "The JAR file....java-client has no source attached". It should look something like this:

<img width="772" alt="Screen Shot 2019-07-15 at 9 26 03 PM" src="https://user-images.githubusercontent.com/2512443/61259254-590c3680-a747-11e9-9dda-e8a1f27ff74e.png">

The `java-client` jar version might give an indicator of whether the support for `AppiumDriver.removeApp` was removed in the version you have.

Thanks,

Chris

**Comment by BadFoo** [comment]
I have encountered another problem with removeAppBeforeTest.
In my case the app have multiple Activities. LoginActivity being the first one we enter on startup.

However if the app was left in another Activity then we get this when trying to remove it before start:
"Cannot start the 'xxxx' application. Original error: 'xxxx.activities.LoginActivity' never started"

It makes sense since you have to start the application to get the driver hook to be able to remove the app. When the app is left running on the device another StartApp call is just reconnecting to this running instance.
But is it possible to give StartApp another 'appWaitActivity as a parameter? 
Need to start Appium one extra time since it is an Appium Capability? Possible at all?

**Comment by ctrevarthen** [comment]
@BadFoo Thanks for reaching out. Let me look into this.
