### ISSUE TITLE
 Unable to import com.detroitlabs.katalonmobileutil.testobject.Finder

### ISSUE THREAD

**Issue by WahomeMaina** [detroit-labs/katalon-mobile-util#4]
I'm getting this error while trying to do and import for com.detroitlabs.katalonmobileutil.testobject.Finder

![image](https://user-images.githubusercontent.com/7492343/54369165-7f7d7080-4686-11e9-893d-bd79f1fe6b11.png)

Test Cases/Enquiries/Full Statement FAILED.
Reason:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/C:/Users/emaina/Katalon%20Studio/CBKL%20Customer%20App/Scripts/Enquiries/Full%20Statement/Script1551339769974.groovy: 20: unable to resolve class com.detroitlabs.katalonmobileutil.testobject.Finder
 @ line 20, column 1.
   import com.detroitlabs.katalonmobileutil.testobject.Finder
   ^

file:/C:/Users/emaina/Katalon%20Studio/CBKL%20Customer%20App/Scripts/Enquiries/Full%20Statement/Script1551339769974.groovy: 19: unable to resolve class com.detroitlabs.katalonmobileutil.testobject.TextField
 @ line 19, column 1.
   import com.detroitlabs.katalonmobileutil.testobject.TextField as TextField
   ^

2 errors

	at com.kms.katalon.core.main.ScriptEngine.getScript(ScriptEngine.java:199)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1552574369619.run(TempTestSuite1552574369619.groovy:35)

**Comment by ctrevarthen** [comment]
Hi @WahomeMaina,

To get the `katalon-mobile-util.jar` did you build it from source code or get it from the Github [Releases](https://github.com/detroit-labs/katalon-mobile-util/releases) page? Can you try downloading the 1.9.0 version from Releases and re-adding it to your External Libraries (removing the old one in the process)?

Also note that you might need to restart Katalon Studio after adding the .jar because I don't think it does it on its own.

**Comment by WahomeMaina** [comment]
I restarted Katalon Studio and its now working well. Thanks
